CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true

BACKBONE: 'resnet'
MODEL: 'voxelpose'
DATA_DIR: ''
GPUS: '0'
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 8
PRINT_FREQ: 100

DATASET:
  COLOR_RGB: True
  ROOT: "data/Panoptic"
  TRAIN_DATASET: 'panoptic'
  TRAIN_HEATMAP_SRC: 'image'
  TEST_DATASET: 'panoptic'
  TEST_HEATMAP_SRC: 'image'
  ROOTIDX: 2
  CAMERA_NUM: 1
  ORI_IMAGE_WIDTH: 1280
  ORI_IMAGE_HEIGHT: 720

NETWORK:
  PRETRAINED_BACKBONE: "models/pose_resnet50_panoptic.pth.tar"
  IMAGE_SIZE:
  - 960
  - 512
  HEATMAP_SIZE:
  - 240
  - 128
  NUM_JOINTS: 15
  SIGMA: 3

TRAIN:
  BATCH_SIZE: 4
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 20
  RESUME: false
  OPTIMIZER: adam
  LR: 0.0001

TEST:
  MODEL_FILE: 'panoptic_5_cams_allseq/model_best.pth.tar'
  BATCH_SIZE: 8

CAPTURE_SPEC:
  SPACE_SIZE:
    - 4300.0
    - 4000.0
    - 2000.0
  SPACE_CENTER:
    - 2100.
    - 10700. #4000. + 7.180
    - 1000.
  VOXELS_PER_AXIS:
    - 40
    - 40
    - 20
  MAX_PEOPLE: 2
  MIN_SCORE: 0.6
  
INDIVIDUAL_SPEC:
  SPACE_SIZE:
    - 2000.0
    - 2000.0
    - 2000.0
  VOXELS_PER_AXIS:
    - 64
    - 64
    - 64
